export MasterPage from './MasterPage'
export IndexPage from './IndexPage'
export NotFoundPage from './NotFoundPage'
export LoginPage from './LoginPage'
export NewsPage from './NewsPage'
export NewsDetails from './newsService/NewsDetails'
export NewsCreateEdit from './newsService/NewsCreateEdit'